// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAXv5ZBHhvyd27WFZblZ7Cq798ID1JKAc',
    appId: '1:116497079176:web:cf6ac44c2a2a2c336eb83d',
    messagingSenderId: '116497079176',
    projectId: 'swapiify-85b9c',
    authDomain: 'swapiify-85b9c.firebaseapp.com',
    storageBucket: 'swapiify-85b9c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBecCza0cGfUGad8xGEpzMuoA2V1wY_Q9Q',
    appId: '1:116497079176:android:6b44aa68939f9a9f6eb83d',
    messagingSenderId: '116497079176',
    projectId: 'swapiify-85b9c',
    storageBucket: 'swapiify-85b9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOSjezw5WfAziaGNBhhf5_Wc2dAjNn0_U',
    appId: '1:116497079176:ios:9a3bd9844e2f329f6eb83d',
    messagingSenderId: '116497079176',
    projectId: 'swapiify-85b9c',
    storageBucket: 'swapiify-85b9c.firebasestorage.app',
    iosBundleId: 'com.example.swapiify',
  );
}
